#!/usr/bin/env bash

#nginx installation and home page content changes.                                                       
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
​
# redirection                                                                                            
new_config="\trewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
conf_file="/etc/nginx/sites-enabled/default"
server="0,/server\s+\{/s//& \n"
sudo sed -i -E "${server}${new_config}/" $conf_file
​
# customize 404 page                                                                                     
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
new_config="\\\n\terror_page 404 /custom_404.html;\n"
file="/etc/nginx/sites-enabled/default"
sudo sed -i "43i $new_config" $file

host=$(cat /etc/hostname)
new_confif="add_header X-Served-By \"$host\";"
file='/etc/nginx/nginx.conf'
sudo sed -i "39i $new_confif" $file
sudo service nginx restart
