#!/usr/bin/env bash
#config config file
host=$(cat /etc/hostname)
new_config="\\\tadd_header X-Served-By \"$host\";"
file='/etc/nginx/nginx.conf'
sudo sed -i "15i $new_config" $file
sudo service nginx restart
