#!/usr/bin/env bash
# Create file
touch /var/run/holbertonschool.pid
echo $$ > /var/run/holbertonschool.pid
while true; do
trap 'echo I hate the kill command & exit & [ -e /var/run/holbertonschool.pid ] && rm /var/run/holbertonschool.pid & exit' SIGTERM
trap "echo Y U no love me?!" SIGINT
if [ -e /var/run/holbertonschool.pid ]; then
trap 'sudo rm /var/run/holbertonschool.pid & exit' SIGQUIT
fi
echo "To infinity and beyond"
sleep 2
done
