#!/usr/bin/env bash
#Script that displays "Holberton School" 10 times but in the 9th line print "Hi"
i=0
while [ $i != 10 ]; do
	echo "Holberton School"
	if [ $i == 8 ]; then
	echo "Hi"
	fi
	i=$((i + 1))
done
