#!/usr/bin/env bash
#Script that displays numbers from 1 to 20
i=0
while [ $i != 20 ]; do
	i=$((i + 1))
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
